### ISSUE TITLE
Pressing "Show messages" multiple times renders duplicate content

### ISSUE THREAD

**Issue by pinkeshbadjatiya** [thelounge/lounge#495]
![Image](https://ptpb.pw/Wz8F.png)

This issue arises when clicking "Show messages" takes some time to render. When i click it multiple times before it renders the content, then, i see the above output.

**Comment by maxpoulin64** [comment]
This is because the button just requests messages before the last one loaded, so it requests the same until new ones arrives. Should be an easy fix, just need to disable the button while one request is made.

**Comment by astorije** [comment]
I cannot reproduce this on my end, I think a combination of faster loading + scroll "stickiness" reduced the impact.
Besides, this should be fixed whenever someone wants to take a stab at implementing https://github.com/thelounge/lounge/issues/207 😄, so it's essentially a dup of that other ticket.

Either way, closing this for these reasons.

**Comment by pinkeshbadjatiya** [comment]
fair enough.

**Comment by YaManicKill** [comment]
Hmmm, this will still be a problem in some cases. Ideally, we should just disable the button once it is clicked until we get the more messages through.

**Comment by astorije** [comment]
@YaManicKill whenever #207 gets done, there won't be a button anymore.

**Comment by YaManicKill** [comment]
True, but this is still an issue until that gets done (afaik, no one is working on it).

**Comment by astorije** [comment]
Right, but there is no need to keep 2 tickets open for this. Also, are you able to reproduce?

**Comment by YaManicKill** [comment]
> Right, but there is no need to keep 2 tickets open for this. 

But 1 is a bug and 1 is a feature request. They aren't the same thing.

> Also, are you able to reproduce?

My internet connection is too fast. I'll need to simulate slower internet to get it to work.

**Comment by MiniDigger** [comment]
its definitely still an issue. used chrome dev tools to throttle my connection and was able to reproduce it. never experienced this in a real world scenario tho (I don't go around pressing buttons like crazy normally :D), ill try next week on my daily commute, got some bad network reception there. 

the fix @YaManicKill proposed seems simple. don't really see #207 happening any time soon.

**Comment by astorije** [comment]
> But 1 is a bug and 1 is a feature request. They aren't the same thing.

I get that. I'm just saying I believe the amount of work to do either of those should be fairly similar, so if someone wants to give it a shot, I'd rather they don't waste their time on something that will not stay, if that makes sense.
Also, if we had like < 50 open tickets, I'd be happy to keep both open, but right now this is far from being the case and it's hurting visibility on the project IMO :)

> the fix @YaManicKill proposed seems simple. don't really see #207 happening any time soon.

Solving #207 is probably super simple as well. I would bet this could be a one-liner.
If you want to fix this very issue instead of #207, you can sure do so, we'd probably merge it, but if someone stops by to help on this, they'd be better off spending their time on #207 than this issue. Again, I get the fix/enhancement difference, but the ultimate goal is the same (making it work ok) without more work, I believe.

**Comment by YaManicKill** [comment]
Well, as you've seen, @astorije in your PR, it's not quite that simple.

Obviously, #207 would be a good thing to have, but I thought I'd create a really simple PR to fix this issue for just now.

**Comment by astorije** [comment]
Agreed @YaManicKill, I was hoping so bad it would be trivial but... :)
Thanks for taking care of this!
